# Generated by Django 3.2 on 2021-04-08 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudDeskSpecialistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('exchangeRate', models.FloatField(max_length=156, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostingProviderModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hostingProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quote.hostingprovidermodel2')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteIDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteInputModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudTermMonths', models.IntegerField(default=36)),
                ('cloudMargin', models.FloatField(default=47.0)),
                ('multipleActiveRegions', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('cloudDeskSpecialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.clouddeskspecialistmodel')),
                ('hostingProvider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.hostingprovidermodel2')),
                ('localCurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.currencymodel2')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.locationmodel2')),
                ('quoteID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.quoteidmodel')),
            ],
        ),
    ]
