# Generated by Django 3.2 on 2021-04-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0002_auto_20210408_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationmodel',
            name='hostingProvider',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='cloudDeskSpecialist',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='cloudMargin',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='cloudTermMonths',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='hostingProvider',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='localCurrency',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='multipleActiveRegions',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='quoteID',
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='cost',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.DeleteModel(
            name='CloudDeskSpecialistModel',
        ),
        migrations.DeleteModel(
            name='CurrencyModel',
        ),
        migrations.DeleteModel(
            name='HostingProviderModel',
        ),
        migrations.DeleteModel(
            name='LocationModel',
        ),
        migrations.DeleteModel(
            name='QuoteIDModel',
        ),
    ]
