# Generated by Django 3.2 on 2021-04-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0003_auto_20210408_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteIDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteID', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='cost',
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='quoteID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.quoteidmodel'),
        ),
    ]
