# Generated by Django 3.2 on 2021-04-08 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0005_rename_quoteid_quoteidmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudDeskSpecialistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('exchangeRate', models.FloatField(max_length=156, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostingProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hostingProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quote.hostingprovidermodel')),
            ],
        ),
        migrations.AlterModelOptions(
            name='quoteinputmodel',
            options={'verbose_name_plural': 'Add Quotes'},
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='quoteID',
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='cloudMargin',
            field=models.FloatField(default=47.0),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='cloudTermMonths',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='multipleActiveRegions',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.DeleteModel(
            name='QuoteIDModel',
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='cloudDeskSpecialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.clouddeskspecialistmodel'),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='hostingProvider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.hostingprovidermodel'),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='localCurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.currencymodel'),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.locationmodel'),
        ),
    ]
