# Generated by Django 3.2 on 2021-04-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0007_quoteinputmodel_createddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='createdDate',
        ),
    ]
