# Generated by Django 3.2 on 2021-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0008_remove_quoteinputmodel_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteinputmodel',
            name='createdDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
