# Generated by Django 3.2 on 2021-04-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0009_quoteinputmodel_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteinputmodel',
            name='gcpAustralia',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='gcpCanada',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='gcpUS',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='opentextAustralia',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='opentextCanada',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
