# Generated by Django 3.2 on 2021-04-09 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0010_auto_20210409_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='gcpAustralia',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='gcpCanada',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='gcpUS',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='opentextAustralia',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='opentextCanada',
        ),
    ]
