# Generated by Django 3.2 on 2021-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0011_auto_20210409_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteinputmodel',
            name='gcpAustralia',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='gcpCanada',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='gcpUS',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='opentextAustralia',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='opentextCanada',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
    ]
