# Generated by Django 3.2 on 2021-04-12 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quote', '0013_auto_20210412_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteinputmodel',
            name='user_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='gcpUS',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='hostingProvider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.hostingprovidermodel'),
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.locationmodel'),
        ),
    ]
