# Generated by Django 3.0.7 on 2021-03-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteInputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteName', models.CharField(max_length=56, null=True)),
                ('salesForceCloudOpportunityID', models.CharField(max_length=120)),
                ('customerName', models.CharField(max_length=120, null=True)),
                ('cloudOpportunityURL', models.URLField(blank=True, help_text='copy and paste SFDC Opportunity URL', null=True)),
                ('cloudDeskSpecialist', models.CharField(choices=[('Arlene Branham', 'Arlene Branham'), ('John Smith', 'John Smith'), ('Sharron Harman', 'Sharron Harman'), ('Harry Anderson', 'Harry Anderson')], max_length=56, null=True)),
                ('cloudOpportunityType', models.CharField(choices=[('Cloud Subscription', 'Cloud Subscription'), ('Cloud Perpetual', 'Cloud Perpetual'), ('SaaS', 'SaaS')], max_length=56, null=True)),
                ('leadingProduct', models.CharField(choices=[('OpenText ContentSuite', 'OpenText ContentSuite'), ('OpenText Experience Suite', 'OpenText Experience Suite'), ('OpenText Process Suite', 'OpenText Process Suite'), ('OpenText Information Exchange Suite', 'OpenText Information Exchange Suite'), ('OpenText Discovery Suite', 'OpenText Discovery Suite'), ('OpenText Suite for SAP', 'OpenText Suite for SAP'), ('OpenText Suite for Oracle', 'OpenText Suite for Oracle'), ('OpenText Suite for Microsoft', 'OpenText Suite for Microsoft'), ('OpenText Appworks', 'OpenText Appworks'), ('OpenText Cloud', 'OpenText Cloud')], max_length=120, null=True)),
                ('nonStandardTermsOrPenalties', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('hasTheEnterpriseCloudManagedServicesBeenExcludedByaCDSRep', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=56, null=True)),
                ('managedServicesRep', models.CharField(choices=[('M1', 'CDS Rep 1'), ('M2', 'CDS Rep 2'), ('M3', 'CDS Rep 3'), ('M4', 'CDS Rep 4'), ('M5', 'CDS Rep 5')], max_length=56, null=True)),
                ('localCurrency', models.CharField(choices=[('USD', 'USD'), ('AED', 'AED'), ('AFN', 'AFN'), ('ALL', 'ALL'), ('AMD', 'AMD'), ('ANG', 'ANG'), ('AOA', 'AOA'), ('ARS', 'ARS'), ('AUD', 'AUD'), ('AZN', 'AZN'), ('BAM', 'BAM'), ('BBD', 'BBD'), ('BDT', 'BDT'), ('BGN', 'BGN'), ('BHD', 'BHD'), ('BIF', 'BIF'), ('BMD', 'BMD'), ('BND', 'BND'), ('BOB', 'BOB'), ('BRL', 'BRL'), ('BSD', 'BSD'), ('BTN', 'BTN'), ('BWP', 'BWP'), ('BZD', 'BZD'), ('CAD', 'CAD'), ('CDF', 'CDF'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNH', 'CNH'), ('CNY', 'CNY'), ('COP', 'COP'), ('CRC', 'CRC'), ('CVE', 'CVE'), ('CYP', 'CYP'), ('CZK', 'CZK'), ('DJF', 'DJF'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('DZD', 'DZD'), ('EEK', 'EEK'), ('EGP', 'EGP'), ('ETB', 'ETB'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('GBP', 'GBP'), ('GEL', 'GEL'), ('GHS', 'GHS'), ('GIP', 'GIP'), ('GMD', 'GMD'), ('GNF', 'GNF'), ('GTQ', 'GTQ'), ('GYD', 'GYD'), ('HKD', 'HKD'), ('HNL', 'HNL'), ('HRK', 'HRK'), ('HTG', 'HTG'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('IRR', 'IRR'), ('ISK', 'ISK'), ('JMD', 'JMD'), ('JOD', 'JOD'), ('JPY', 'JPY'), ('KES', 'KES'), ('KGS', 'KGS'), ('KHR', 'KHR'), ('KMF', 'KMF'), ('KRW', 'KRW'), ('KWD', 'KWD'), ('KYD', 'KYD'), ('KZT', 'KZT'), ('LAK', 'LAK'), ('LBP', 'LBP'), ('LKR', 'LKR'), ('LSL', 'LSL'), ('LTL', 'LTL'), ('LVL', 'LVL'), ('MAD', 'MAD'), ('MDL', 'MDL'), ('MGA', 'MGA'), ('MKD', 'MKD'), ('MMK', 'MMK'), ('MNT', 'MNT'), ('MOP', 'MOP'), ('MRO', 'MRO'), ('MTL', 'MTL'), ('MUR', 'MUR'), ('MVR', 'MVR'), ('MWK', 'MWK'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('MZN', 'MZN'), ('NAD', 'NAD'), ('NGN', 'NGN'), ('NIO', 'NIO'), ('NOK', 'NOK'), ('NPR', 'NPR'), ('NZD', 'NZD'), ('OMR', 'OMR'), ('PAB', 'PAB'), ('PEN', 'PEN'), ('PGK', 'PGK'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('PYG', 'PYG'), ('QAR', 'QAR'), ('RON', 'RON'), ('RSD', 'RSD'), ('RUB', 'RUB'), ('RWF', 'RWF'), ('SAR', 'SAR'), ('SBD', 'SBD'), ('SCR', 'SCR'), ('SDG', 'SDG'), ('SEK', 'SEK'), ('SGD', 'SGD'), ('SIT', 'SIT'), ('SKK', 'SKK'), ('SLL', 'SLL'), ('SRD', 'SRD'), ('STD', 'STD'), ('SVC', 'SVC'), ('SYP', 'SYP'), ('SZL', 'SZL'), ('THB', 'THB'), ('TJS', 'TJS'), ('TND', 'TND'), ('TOP', 'TOP'), ('TRY', 'TRY'), ('TTD', 'TTD'), ('TWD', 'TWD'), ('TZS', 'TZS'), ('UAH', 'UAH'), ('UGX', 'UGX'), ('UYU', 'UYU'), ('UZS', 'UZS'), ('VEF', 'VEF'), ('VND', 'VND'), ('VUV', 'VUV'), ('WST', 'WST'), ('XAF', 'XAF'), ('XCD', 'XCD'), ('XOF', 'XOF'), ('XPF', 'XPF'), ('YER', 'YER'), ('ZAR', 'ZAR'), ('ZMW', 'ZMW')], max_length=56, null=True)),
                ('requireTimelineBasedChanges', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('inRegionNAEMEAPersonnelOnly', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('changeRequestOrAddOnOnly', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('ifCRAddOnGCPAlreadyProvisionedNetAppCVO', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('cloudTermMonths', models.IntegerField(default=36)),
                ('subscriptionSoftwareOTDirectDiscount', models.FloatField(default=85)),
                ('subscriptionSoftwareThirdPartyDiscount', models.FloatField(default=30)),
                ('perpetualSoftwareOTDirectDiscount', models.FloatField(default=10)),
                ('perpetualSoftwareThirdPartyDiscount', models.FloatField(default=5)),
                ('CPSCostRateUSDhr', models.FloatField(default=80.0)),
                ('CDMCostRateUSDhr', models.FloatField(default=80.0)),
                ('DRPlanningLaborCostRateUSDhr', models.FloatField(default=100.0)),
                ('cloudMargin', models.FloatField(default=47.0)),
                ('annualPriceAdjustment', models.FloatField(default=3.0)),
                ('incrementalECMSHeadcountRequiredAsPartOfTheECMS', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('CPSMonthlyHours', models.IntegerField(help_text='30hrs is the minimum, approvals required for less', null=True)),
                ('CDSMonthlyHours', models.IntegerField(help_text='15hrs is the minimum, approvals required for less', null=True)),
                ('manualInstallationCost', models.FloatField(help_text='If populated, this overrides the automation of installation costs within the VM tab. Use for Daas', max_length=28, null=True)),
                ('endOfFirstYearUsersOfTotal', models.FloatField(max_length=10, null=True)),
                ('annualUsersIncreaseOfTotal', models.FloatField(max_length=10, null=True)),
                ('totalUsersOverTerm', models.IntegerField(null=True)),
                ('removeAmortized10kUSDFee100Margin', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('hostingProvider', models.CharField(choices=[('OpenText', 'OpenText'), ('OpenText Australia', 'OpenText Australia'), ('OpenText Canada', 'OpenText Canada'), ('GCP', 'GCP'), ('Azure', 'Azure'), ('AWS', 'AWS'), ('Customer', 'Customer')], max_length=56, null=True)),
                ('location', models.CharField(blank=True, choices=[('--------------', '--------------'), ('OT - US Twins', 'OT - US Twins'), ('OT - EMEA Twins', 'OT - EMEA Twins'), ('OT - Japan Twins', 'OT - Japan Twins'), ('OT - Sydney', 'OT - Sydney'), ('OT - Toronto', 'OT - Toronto'), ('GCP - US', 'GCP - US'), ('GCP - NA-NE', 'GCP - NA-NE'), ('GCP - Europe', 'GCP - Europe'), ('GCP - Australia', 'GCP - Australia'), ('GCP - Asia', 'GCP - Asia'), ('GCP - Asia-East', 'GCP - Asia-East'), ('GCP - Asia-NE', 'GCP - Asia-NE'), ('GCP - Brazil', 'GCP - Brazil'), ('Central US', 'Central US'), ('East US', 'East US'), ('East US 2', 'East US 2'), ('North Central US', 'North Central US'), ('South Central US', 'South Central US'), ('West Central US', 'West Central US'), ('West US', 'West US'), ('West US 2', 'West US 2'), ('North Europe', 'North Europe'), ('West Europe', 'West Europe'), ('East Asia', 'East Asia'), ('US East (N.Virginia)', 'US East (N.Virginia)'), ('US East (Ohio)', 'US East (Ohio)'), ('US West (Oregon)', 'US West (Oregon)'), ('US West (N. Calif.)', 'US West (N. Calif.)'), ('Africa (Cape Town)', 'Africa (Cape Town)'), ('Asia Pacific (Hong Kong)', 'Asia Pacific (Hong Kong)'), ('Asia Pacific (Mumbai)', 'Asia Pacific (Mumbai)'), ('Asia Pacific (Osaka-Local)', 'Asia Pacific (Osaka-Local)'), ('Asia Pacific (Seoul)', 'Asia Pacific (Seoul)'), ('Asia Pacific (Singapore)', 'Asia Pacific (Singapore)'), ('Asia Pacific (Sydney)', 'Asia Pacific (Sydney)'), ('Asia Pacific (Tokyo)', 'Asia Pacific (Tokyo)'), ('Canada (Central)', 'Canada (Central)'), ('Europe (Frankfurt)', 'Europe (Frankfurt)'), ('Europe (Ireland)', 'Europe (Ireland)'), ('Europe (London)', 'Europe (London)'), ('Europe (Milan)', 'Europe (Milan)'), ('Europe (Paris)', 'Europe (Paris)'), ('Europe (Stockholm)', 'Europe (Stockholm)'), ('Middle East (Bahrain)', 'Middle East (Bahrain)'), ('South America (Sao Paulo)', 'South America (Sao Paulo)'), ('AWS GovCloud (US-East)', 'AWS GovCloud (US-East)'), ('AWS GovCloud (US-West)', 'AWS GovCloud (US-West)'), ('Customer DC', 'Customer DC')], max_length=56, null=True)),
                ('multipleActiveRegions', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('customerRequestedPrimaryDC', models.CharField(max_length=56, null=True)),
                ('customerRequestedSecondaryOrMoreDCs', models.CharField(max_length=56, null=True)),
                ('explanationOfMultipleActiveRegions', models.CharField(max_length=56, null=True)),
                ('customerRequestedApplicationAvailabilitySLA', models.FloatField(choices=[(99, 99), (99.5, 99.5), (99.9, 99.9)], max_length=10, null=True)),
                ('disasterRecovery', models.CharField(choices=[('--------------', '--------------'), ('OT - Standard', 'OT - Standard'), ('OT - EDR via Twin DCs', 'OT - EDR via Twin DCs'), ('OT DC with GCP for EDR', 'OT DC with GCP for EDR'), ('GCP Single-region Multi-Zone DR', 'GCP Single-region Multi-Zone DR'), ('GCP Multi-region EDR (geographic separation)', 'GCP Multi-region EDR (geographic separation)'), ('Azure Single-region Multi-Zone DR', 'Azure Single-region Multi-Zone DR'), ('Azure Multi-region EDR (geographic separation)', 'Azure Multi-region EDR (geographic separation)'), ('AWS Single-region Multi-Zone DR', 'AWS Single-region Multi-Zone DR'), ('AWS Multi-region EDR (geographic separation)', 'AWS Multi-region EDR (geographic separation)')], max_length=56, null=True)),
                ('customerRequestedRTORPOSLA', models.CharField(choices=[('RTO 7days / RPO 24hrs', 'RTO 7days / RPO 24hrs'), ('RTO 8hrs / RPO 8hrs', 'RTO 8hrs / RPO 8hrs'), ('RTO 4hrs / RPO 4hrs', 'RTO 4hrs / RPO 4hrs')], max_length=56, null=True)),
                ('enhancedDRPlanningHrsPcm', models.FloatField(choices=[('--------------', '--------------'), (16.67, 16.67)], max_length=50, null=True)),
                ('isThisADaaSBasedCloudService', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('requiresEUDataProtectionZoneEUDPZ', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('backupNonProductionEnvironments', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('encryptionAtRest', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('numberOfSiteToSiteVPNs', models.CharField(choices=[(0, 0), (1, 1)], max_length=5, null=True)),
                ('numberOfClientBasedVPNs', models.IntegerField(null=True)),
                ('willTheCustomerUseMPLSVPLSCircuitsToConnect', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('GCPSoleTenantNodesVCPUs96RAM624GBPerSTN', models.IntegerField(null=True)),
                ('additionalCloudDeliveryOpsCostsPcmUSD', models.FloatField(max_length=13, null=True)),
                ('additionalCloudDeliveryOpsCostsOneTimeUSD', models.FloatField(max_length=13, null=True)),
                ('thirdPartyAzureRemoteAccess', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('OSPatching', models.CharField(choices=[('Full', 'Full'), ('Partial', 'Partial')], max_length=10, null=True)),
                ('threatManagementAndSecurityScans', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('problemEscalationAndResponse', models.CharField(choices=[('24x7', '24x7'), ('10x5', '10x5')], max_length=10, null=True)),
                ('loadBalancing', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('firewall', models.CharField(choices=[('Multiple Access Points', 'Multiple Access Points'), ('Single Access Point', 'Single Access Point')], max_length=50, null=True)),
                ('databaseAdministrationAndTuning', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('activeActiveDBRequired', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('applicationMonitoringRequiredNewRelic', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
            ],
        ),
    ]
