# Generated by Django 3.0.7 on 2021-04-03 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingProviderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='CDSMonthlyHours',
            field=models.PositiveIntegerField(help_text='15hrs is the minimum, approvals required for less', null=True),
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='CPSMonthlyHours',
            field=models.PositiveIntegerField(help_text='30hrs is the minimum, approvals required for less', null=True),
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hostingProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuoteInput.HostingProviderModel')),
            ],
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='hostingProvider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.HostingProviderModel'),
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.LocationModel'),
        ),
    ]
