# Generated by Django 3.0.7 on 2021-04-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0004_auto_20210403_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='nonStandardTermsOrPenalties',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
