# Generated by Django 3.0.7 on 2021-04-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0005_auto_20210403_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudDeskSpecialistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
            ],
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='cloudDeskSpecialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.CloudDeskSpecialistModel'),
        ),
    ]
