# Generated by Django 3.0.7 on 2021-04-03 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0006_auto_20210403_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCurrencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(max_length=56)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuoteInput.LocalCurrencyModel')),
            ],
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='exchangeRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.ExchangeRateModel'),
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='localCurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.LocalCurrencyModel'),
        ),
    ]
