# Generated by Django 3.0.7 on 2021-04-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0007_auto_20210403_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='exchangeRate',
        ),
        migrations.AddField(
            model_name='localcurrencymodel',
            name='exchangeRate',
            field=models.FloatField(max_length=156, null=True),
        ),
        migrations.DeleteModel(
            name='ExchangeRateModel',
        ),
    ]
