# Generated by Django 3.0.7 on 2021-04-03 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0008_auto_20210403_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteinputmodel',
            name='exchangeRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rate', to='QuoteInput.LocalCurrencyModel'),
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='localCurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_currency', to='QuoteInput.LocalCurrencyModel'),
        ),
    ]
