# Generated by Django 3.0.7 on 2021-04-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0009_auto_20210403_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='exchangeRate',
        ),
        migrations.AlterField(
            model_name='quoteinputmodel',
            name='localCurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.LocalCurrencyModel'),
        ),
    ]
