version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/node/app
    ports:
      - '8000:8000'

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: db_emscalc2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - '3306:3306'