# Generated by Django 3.0.7 on 2021-12-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddForm', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
