# Generated by Django 3.0.7 on 2021-04-03 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRPlanningLaborCostRateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CPSCostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpsHours', models.IntegerField()),
                ('term', models.IntegerField()),
                ('DRPlanningLaborCostRate_USDPerHr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPSCalc.DRPlanningLaborCostRateModel')),
            ],
        ),
    ]
