# Generated by Django 3.0.7 on 2021-12-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPSCalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drplanninglaborcostratemodel',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
