# Generated by Django 3.0.7 on 2021-04-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('exchangeRate', models.FloatField(max_length=156, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteInputModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudTermMonths', models.IntegerField(default=36)),
                ('cloudMargin', models.FloatField(default=47.0)),
                ('localCurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.CurrencyModel2')),
            ],
        ),
    ]
