# Generated by Django 3.0.7 on 2021-04-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210403_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingProviderModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hostingProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.HostingProviderModel2')),
            ],
        ),
        migrations.AddField(
            model_name='quoteinputmodel2',
            name='hostingProvider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.HostingProviderModel2'),
        ),
        migrations.AddField(
            model_name='quoteinputmodel2',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.LocationModel2'),
        ),
    ]
