# Generated by Django 3.0.7 on 2021-04-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20210403_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteinputmodel2',
            options={'verbose_name_plural': 'Add Quotes'},
        ),
        migrations.CreateModel(
            name='QuoteIDModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.QuoteInputModel2')),
            ],
        ),
        migrations.AddField(
            model_name='quoteinputmodel2',
            name='quoteID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.QuoteIDModel'),
        ),
    ]
