# Generated by Django 3.0.7 on 2021-04-05 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20210405_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteidmodel',
            name='quoteID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quoteinputmodel2',
            name='quoteID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.QuoteIDModel'),
        ),
    ]
