# Generated by Django 3.0.7 on 2021-04-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20210405_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteinputmodel2',
            name='multipleActiveRegions',
            field=models.BooleanField(default=False),
        ),
    ]
